# NumPy
1. library for the Python programming language

2. multi-dimensional arrays and matrices, vectors

3. large collection of high-level mathematical functions to operate on these arrays

# SciPy
1. free and open-source Python library used for scientific computing and technical computing.

2. contains modules for optimization, linear algebra, integration, interpolation, special functions, FFT, signal and image processing, ODE solvers and other tasks common in science and engineering

In [2]:
#!pip install numpy
#import numpy
import numpy as np

In [37]:
#0-D array
a=np.array(3)
print(a,"dimension is", a.ndim)

3 dimension is 0


In [4]:
#1-d array
a=np.array([5,6,8,10])
a

array([ 5,  6,  8, 10])

In [7]:
#2-d array
b=np.array([[10,23,4],[12,56,45]])
b

array([[10, 23,  4],
       [12, 56, 45]])

In [11]:
#3-d array with datatype as float
c = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(11,12,13)]],dtype=float)
c

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [11., 12., 13.]]])

### Dimension of array--- Syntax: "arrayname".ndim

In [15]:
#how to find the dimension of array
arr=np.array(8)
a=np.array([5,6,8,10])
b=np.array([[10,23,4],[12,56,45]])
c = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(11,12,13)]])
print(arr.ndim)
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2
3


### Type of array ---  Syntax: type("arrayname")

In [13]:
#find the type
a=np.array([5,6,8,10])
b=np.array([[10,23,4],[12,56,45]])
c = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(11,12,13)]])
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Dimension definition --- Syntax: np.array(("array values"), ndmin="dimension no.")

In [19]:
#Defining the dimension
#answer is a 2 dimension, this can be found out by counting the pairs of sq. brackets eg:
#also, check for the parameter ndmin and ndim spellings
x=np.array([1,2,3],ndmin=2)
y=np.array([[1,2,3,4],[1,8,9,10]], ndmin=3)
print(x)
print(y)

[[1 2 3]]
[[[ 1  2  3  4]
  [ 1  8  9 10]]]


### Zeros array --- Syntax:np.zeros((row, cols))

In [23]:
#zeros array (3,5)is a tuple, this is because np.zeros((no of rows, no of cols), parameters required for the array)
zero1=np.zeros((3,5),dtype='i')
zero1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

### Ones array --- Syntax: np.ones((row, cols))

In [67]:
#Ones array
One1=np.ones((1,3),dtype='S')
One2=np.ones((1,3),dtype='bool')
print(One1)
print(One2)
print(type(One2), One2.dtype, One2.ndim)

[[b'1' b'1' b'1']]
[[ True  True  True]]
<class 'numpy.ndarray'> bool 2


### Identity matrix --- Syntax: np.eye("row/cols")

In [42]:
#Identity matrix is a sq matrix hence mentioning row value is enough.
#Returns array filled with zeros except in the kth diagonal, whose values are equal to 1
a=np.eye(4)
print(a, " ")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]  
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [43]:
#in this the positioning of Ones can be redefined
# if k=-1 it will go one row down
b=np.eye(4,k=-1)
print(b)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [44]:
#we see in the below example, we have last 2 rows being filled first
b=np.eye(4,k=2)
print(b)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Acessing array elements

In [45]:
#accessing 1d array, this is similar to list accessing
a=np.array([1,2,3,4])
print(a[2])
print(a[-2])
print(a[1]*a[3])

3
3
8


In [52]:
#accessing 2d array, the acessing is as follows 
#step1:[[0],[1]]
#step2: [[0.0,0.1,0.2,0.3],[1.0,1.1,1.2,1.3]]
#hence syntax is ([Step1, Step2])
a=np.array([[1,4,5,6],[9,8,50,6]])
print(a[1,1])

8


In [54]:
#Access 3-D Arrays the acessing is as follows 
#step1:[[[0],[1]]]
#step2:[[[0.0],[0.1].[1.0],[1.1]]]
#step2: [0.0.0,0.0.1,0.0.2,0.0.3], [0.1.0,0.1.1,0.1.2,0.1.3],[1.0.0,1.0.1,1.0.2,1.0.3],[1.1.0,1.1.1,1.1.2,1.1.3]
a = np.array([[[10, 20, 30], [40, 50, 60]], [[70, 81, 91], [101, 112, 123]]])
print(a[0,1,2])

60


In [55]:
#Negative Indexing, the last value/element is -1 anlast before being -2....
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(a[1, -3])

8


# Slicing arrays

In [3]:
#slicing in 1d is similar to list, syntax is a[start point, end point+1]
a=np.array([1,2,3,4])
print(a[1:3]) 
print(a[:]) #gives full array
print(a[2:]) #gives complete array start from 2 index 
print(a[:3]) #gives elements from start to 2nd index
print(a[-1:-3]) #doesn't give any elemets as slicing traverses from left to right
print(a[-3:2]) 
print(a[::3]) #third value is a step value

[2 3]
[1 2 3 4]
[3 4]
[1 2 3]
[]
[2]
[1 4]


In [5]:
#slicing in 2d array
a=np.array([[1,4,5,6],[9,8,50,6]])
print(a[1,1:3]) #in first indexed list [9,8,50,6] elements from index 1 to index 2 are given as output
print(a[:]) #gives full array
print(a[0:, 2:]) #gives complete array start from 2 index 
print(a[:2, :3]) #gives elements from both the lists from start to 2nd index
print(a[1, -1:-3]) #doesn't give any elemets as slicing traverses from left to right
print(a[0:, -3:2])
print(a[:, :1])
print(a[1,::2]) #::2 mentions to print every second value

[ 8 50]
[[ 1  4  5  6]
 [ 9  8 50  6]]
[[ 5  6]
 [50  6]]
[[ 1  4  5]
 [ 9  8 50]]
[]
[[4]
 [8]]
[[1]
 [9]]
[ 9 50]


In [6]:
#slicing in 3d array
a = np.array([[[10, 20, 30], [40, 50, 60]], [[70, 81, 91], [101, 112, 123]]])
print(a[1,1,1:3]) #in first indexed list [70, 81, 91], [101, 112, 123],2:[101, 112, 123]  
print(a[:]) #gives full array
print(a[0:, 0:, 2:]) #gives complete array start from 2 index 
print(a[1, :2, :3]) #gives elements from both the lists from start to 2nd index
print(a[0, 1, -1:-3]) #doesn't give any elemets as slicing traverses from left to right
print(a[0, 0:, -3:2])
print(a[:, :, :1]) 
print(a[:,:,::2]) #::1 is step value

[112 123]
[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  81  91]
  [101 112 123]]]
[[[ 30]
  [ 60]]

 [[ 91]
  [123]]]
[[ 70  81  91]
 [101 112 123]]
[]
[[10 20]
 [40 50]]
[[[ 10]
  [ 40]]

 [[ 70]
  [101]]]
[[[ 10  30]
  [ 40  60]]

 [[ 70  91]
  [101 123]]]


# NumPy Data Types
i - integer    
b - boolean    
u - unsigned integer    
f - float     
c - complex float    
m - timedelta        
M - datetime  
O - object      
S - string      
U - unicode string    
V - fixed chunk of memory for other type ( void )

###  To convert the data type of an array  Syntax: "arrayname".astype("datatype")

In [70]:
#Change data type from float to integer by using int as parameter value
a = np.array([2.6, 5.1, 5.6])  #takes the value before the decimal to convert from float to int
b= a.astype(int)
print(b.dtype)
print(b)
c=b.astype(bool)  #gives true if the value is in prsent in the index else gives false
print(c.dtype)
print(c)

int32
[2 5 5]
bool
[ True  True  True]


### To copy an array Syntax: "arrayname".copy()

In [72]:
a =np.arange(1,10)
b=a.copy()
b[1] = 20
print(a)
print(b)  #as we see the value in B[1] is changes but not in a[1] 

[1 2 3 4 5 6 7 8 9]
[ 1 20  3  4  5  6  7  8  9]


### View , Syntax: "arrayname".view()

In [74]:
a =np.arange(1,10)
b=a.view()
b[1] = 20
print(a)
print(b)  #as we see the value in B[1] and A[1]is changed

[ 1 20  3  4  5  6  7  8  9]
[ 1 20  3  4  5  6  7  8  9]


### Shape of an array(to find out) ---  Syntax:"arrayname".shape

In [13]:
#shape return tuple value as (row, value)
a=np.arange(1,10,1)
b=np.array([[1,2,3],[2,4,5]])
print(a)
print(a.shape) #the shape return a tuple value
print(b.shape) 

[1 2 3 4 5 6 7 8 9]
(9,)
(2, 3)


### Reshaping means changing the shape of an array ---  Syntax "arrayname".reshape(row,shape)

In [15]:
#reshaping of 1d to 2d array
a=np.arange(1,13,1)
b=a.reshape(4,3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
#reshaping 1d to 3d
a=np.arange(1,31,1)
b=a.reshape(2,5,3)
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]]]


### Flattening the arrays --- Syntax "arrayname".reshape(-1)

In [21]:
#flattening an array means converting a multidimensional array into 1d array
a=np.array([[1,2,3],[3,4,5]])
b=a.reshape(-1)
print(b)

[1 2 3 3 4 5]


### Iterating an array --- for loop 

In [23]:
# 1d array
a=np.array([10,20,30])
for i in a:
    print(i)

10
20
30


In [31]:
#2d array
b=np.arange(1,21,1).reshape(4,5)
print(b)
for i in b:
    print(i)
    for j in i:
        print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[1 2 3 4 5]
1
2
3
4
5
[ 6  7  8  9 10]
6
7
8
9
10
[11 12 13 14 15]
11
12
13
14
15
[16 17 18 19 20]
16
17
18
19
20


In [33]:
#3d array
a = np.array([[[11, 21,44], [56, 14, 60]], [[7, 8, 9], [10, 11, 12]]])
for i in a:
    print(i)
    for j in i:
        print(j)
        for k in j:
            print(k)

[[11 21 44]
 [56 14 60]]
[11 21 44]
11
21
44
[56 14 60]
56
14
60
[[ 7  8  9]
 [10 11 12]]
[7 8 9]
7
8
9
[10 11 12]
10
11
12


In [34]:
#iterating 3d array using nditer
a = np.array([[[11, 21,44], [56, 14, 60]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(a):
    print(x)

11
21
44
56
14
60
7
8
9
10
11
12


### Iterating of 3d array using nditer --- Syntax nditer("arrayname") used with for loop

In [42]:
#Iterate through every scalar element of the 2D array using slicing method
a=np.arange(1,11).reshape(2,5)
print(a)
for i in np.nditer(a[:,::2]):
    print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
3
5
6
8
10


### Enumerate an array --- Syntax np.ndenumerate("arrayname") used with for loop

In [44]:
#enumerate 1d array

x=np.array([7,9,10])
for i in np.ndenumerate(x):
    print(i)

((0,), 7)
((1,), 9)
((2,), 10)


In [46]:
#Enumerate 2D array
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for index,i in np.ndenumerate(x):
  print(index, i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining NumPy Arrays

### Merging elements of two or more arrays in a single array.

In [76]:
#difference between merging and reshape(-1) is
#merging/concate will join different arrays 
#reshape(-1) will reshape a multidimensional array to id

x=np.arange(1,5)
y=np.arange(4,8)
z=np.concatenate((x,y),axis=0)
print(z)

[1 2 3 4 4 5 6 7]


In [63]:
#Join two 2d arrays
a=np.arange(1,11).reshape(5,2)
b=np.arange(11,21).reshape(5,2)
c=np.concatenate((a,b),axis=0) #axis=0 means the next array will added column wise
d=np.concatenate((a,b),axis=1) #axis=1 means the next array will added row wise
print(c)
print(d)
print(d[2:4,2:])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]
 [ 7  8 17 18]
 [ 9 10 19 20]]
[[15 16]
 [17 18]]


# Stacking Arrays

### Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [66]:
# using the syntax np.stack always mention the axis
a=np.arange(1,5)
b=np.arange(5,9)
c=np.stack((a,b),axis=0)
d=np.stack((a,b),axis=1)
print(c)
print(d)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [74]:
a=np.array([1,4,5])
b=np.array([7,8,9])
c=np.stack((a,b),axis=0)
c1=np.concatenate((a,b),axis=0)
d=np.stack((a,b),axis=1)
#d1=np.concatenate((a,b),axis=1) #here using concatenate is giving out error 
print(c)
print(c1)
print(d)
#print(d1)

[[1 4 5]
 [7 8 9]]
[1 4 5 7 8 9]
[[1 7]
 [4 8]
 [5 9]]


In [70]:
#Stacking Along Rows
#we need not mention the axis as hstack is horizontal stack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [71]:
#Stacking Along Columns
#we need not mention the axis as vstack is vertical stack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [78]:
#Stack arrays in sequence depth wise (along third axis, which is rgb axis) 
#This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-
#data with a height (first axis), width (second axis), and r/g/b channels (third axis).The
#functions concatenate, stack and block provide more general stacking and concatenation operations.
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
c=np.dstack((a,b))
c

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

# Splitting NumPy Arrays

## It is the reverse operation of Joining

### Splits single array into multiple

In [91]:
#the split function splits the values in equal manner
a=np.array([1,2,3,4])
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12,34,45,34])
a1=np.array_split(a,5)
b1=np.array_split(b,10)
print(a1)
print(b1)
print(b1[0:1]) #split creates a 1d array and each element can be retrived and acces it wholly only
c=b1[1:2].copy()
print(c)

[array([1]), array([2]), array([3]), array([4]), array([], dtype=int32)]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10]), array([11]), array([12]), array([34]), array([45]), array([34])]
[array([1, 2])]
[array([3, 4])]


In [92]:
#split a 2d array
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
a1= np.array_split(a,4,axis=1) #it splits along the column 
print(a1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([], shape=(6, 0), dtype=int32)]


In [94]:
#split a 2d array
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
a1= np.hsplit(a,3) #need not mention the axis as it is hsplit also, there os no vsplit
print(a1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Arrays

In [8]:
#seach return the index value
x=np.array([1,5,6,7,8,9,13,45,6])
x1 = np.where(x == 6)
x1

(array([2, 8], dtype=int64),)

In [15]:
#finding the element in even indices
a=([1,2,3,4,5,6,10,6,7,13,56])
a1=np.where(x%2 == 0)
print(a1)

(array([1, 3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)


In [9]:
#The NumPy searchsorted () function can be used to find the index value 
#where the new elements should be inserted in the sorted array and the order of an array be preserved. 
#If in a sorted array the same elements is already present then we can specify to insert left or right of it.
arr = np.array([1, 2, 3, 4])
x = np.searchsorted(arr, [1,2,3])
print(x)
arr = np.array([67, 74, 62, 51])
a=np.searchsorted(arr,65)  #so this indicates the element to be added in which index postion after sorting the array
print(a)

[0 1 2]
4


# Sorting the array --- Syntax : np.sort(array name)

In [11]:
#sort an array
a=([101,234,134,187,68,98,0])
b=np.sort(a)
arr1 = np.array(['python', 'datascience', 'artificial intelligence','machine learning'])
print(np.sort(arr1))
print(b)

['artificial intelligence' 'datascience' 'machine learning' 'python']
[  0  68  98 101 134 187 234]


In [15]:
#for boolean values, always false is first 
a=np.array([True,True,False,True,False])
print(np.sort(a))

[False False  True  True  True]


In [19]:
#sort a 2d array, the sort along the value in a row
a=np.array([[2,3,1], [13,10,11], [1,6,5], [13, 14, 15], [4, 5, 6], [7, 8, 9], [16, 17, 18]])
print(np.sort(a))

[[ 1  2  3]
 [10 11 13]
 [ 1  5  6]
 [13 14 15]
 [ 4  5  6]
 [ 7  8  9]
 [16 17 18]]


# LINEAR ALGEBRA

### Dot product of the two arrays --- Syntax: np.dot("array1", "array2")

In [23]:
a = np.array([[1,2], [3,4]]) 
b = np.array([[11, 12], [13, 14]]) 
print (np.dot(a,b))
#1*11+2*13 , 1*12+2*14 
#3*11+4*13, 3*12+4*14 

[[37 40]
 [85 92]]


In [24]:
a = np.array([[1,2], [3,4]]) 
b = np.array([[11, 12], [13, 14]]) 
print (np.inner(a,b))
#1*11+2*12, 1*13+2*14 
#3*11+4*12, 3*13+4*14 

[[35 41]
 [81 95]]


### Inverse of a matrix  --- Syntax:np.linalg.inv("array name")

In [26]:
#inverse is a log inverse of the number 
x = np.array([[2,3],[12,5]]) 
y = np.linalg.inv(x) 
print(y)

[[-0.19230769  0.11538462]
 [ 0.46153846 -0.07692308]]


### Determinant of Matrix --- Syntax: np.linalg.set("array name")

In [27]:
# Determinant  [[a,b], [c,d]], = ‘ad-bc’
a=np.array([[3,4],[13,14]])
np.linalg.det(a)

-9.999999999999998

### Solve Linear Equation Using NumPy

In [34]:
#slove an equation to find x,y,z values
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
ainv = np.linalg.inv(a) 
print(ainv)
b = np.array([[6],[-4],[27]])  
print(b)
print(np.dot(ainv,b))
x = np.linalg.solve(a,b) 
print(x)

[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
[[ 6]
 [-4]
 [27]]
[[ 5.]
 [ 3.]
 [-2.]]
[[ 5.]
 [ 3.]
 [-2.]]


### Statistical Functions

In [37]:
#finiding min and max 
a=np.array([[5,78,6],[19,99,55],[34,56,67]])
print(np.amin(a))
print(np.amax(a))

5
99


### Median  --- Syntax: np.median("array name")

In [42]:
#find the median
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[5,78,6],[19,99,55],[34,56,67]])
print(np.sort(b))
print(np.median(b))
print(np.median(a))

[[ 5  6 78]
 [19 55 99]
 [34 56 67]]
55.0
5.0


### Standard deviation  --- Syntax: np.std("array name")

In [44]:
#If the array is [1, 2, 3, 4], then its mean is 2.5. 
#Hence the squared deviations are [2.25, 0.25, 0.25, 2.25] and the square root of its mean divided by 4, i.e., sqrt (5/4) 
#is 1.1180339887498949.
a = np.array([1,2,3,4]) 
print(a)
print(np.std(a))

[1 2 3 4]
1.118033988749895


### Variance  --- Syntax : np.var("array name")

In [45]:
#the deviations are [2.25, 0.25, 0.25, 2.25] and the sum of its mean divided by 4, i.e.,(5/4) 
a=np.array([1,2,3,4])
print(np.var(a))

1.25


### Average --- Syntax : np.average("array name")

In [47]:
#Average - same as mean
a = np.array([1,2,3]) 
print(np.average(a))

2.0


### Percentile ---  Syntax : np.percentile("array name", value for which percentile is to be calculate)

In [51]:
#Percentile = (Number of Values Below “x” / Total Number of Values) × 100
a = np.array([2,10,20,56,34,90,78,98,32])  
print(np.sort(a))
print(a)  
print(np.percentile(a,90))

[ 2 10 20 32 34 56 78 90 98]
[ 2 10 20 56 34 90 78 98 32]
91.6


### Peak to peak function : determine the range along an axis

In [54]:
#difference between a1=b1 eg:20-6
a = np.array([[20,10,30],[6,7,34]])  
print(np.ptp(a,0))

[14  3  4]
